import { Shift } from '@/lib/types';

export const MOCK_SHIFTS: Shift[] = [
  {
    id: 'shift-001',
    role: 'Registered Nurse',
    facilityName: 'St. Mary Medical Center',
    facilityLocation: 'Los Angeles, CA',
    date: '2026-05-12',
    startTime: '07:00',
    endTime: '19:00',
    ratePerHour: 62,
    urgency: 'urgent',
    claimedBy: null,
  },
  {
    id: 'shift-002',
    role: 'ICU Nurse',
    facilityName: 'Cedars-Sinai Hospital',
    facilityLocation: 'Beverly Hills, CA',
    date: '2026-05-13',
    startTime: '19:00',
    endTime: '07:00',
    ratePerHour: 78,
    urgency: 'urgent',
    claimedBy: null,
  },
  {
    id: 'shift-003',
    role: 'Certified Nursing Assistant',
    facilityName: 'Sunrise Senior Living',
    facilityLocation: 'Santa Monica, CA',
    date: '2026-05-14',
    startTime: '08:00',
    endTime: '16:00',
    ratePerHour: 38,
    urgency: 'standard',
    claimedBy: null,
  },
  {
    id: 'shift-004',
    role: 'Medical-Surgical Nurse',
    facilityName: 'Harbor UCLA Medical Center',
    facilityLocation: 'Torrance, CA',
    date: '2026-05-15',
    startTime: '07:00',
    endTime: '19:00',
    ratePerHour: 68,
    urgency: 'standard',
    claimedBy: null,
  },
  {
    id: 'shift-005',
    role: 'Emergency Room Nurse',
    facilityName: 'Keck Hospital of USC',
    facilityLocation: 'Los Angeles, CA',
    date: '2026-05-15',
    startTime: '15:00',
    endTime: '23:00',
    ratePerHour: 82,
    urgency: 'urgent',
    claimedBy: null,
  },
  {
    id: 'shift-006',
    role: 'Surgical Tech',
    facilityName: 'Providence Holy Cross',
    facilityLocation: 'Mission Hills, CA',
    date: '2026-05-16',
    startTime: '06:00',
    endTime: '14:00',
    ratePerHour: 54,
    urgency: 'standard',
    claimedBy: null,
  },
  {
    id: 'shift-007',
    role: 'Licensed Vocational Nurse',
    facilityName: 'LAC+USC Medical Center',
    facilityLocation: 'Los Angeles, CA',
    date: '2026-05-17',
    startTime: '23:00',
    endTime: '07:00',
    ratePerHour: 48,
    urgency: 'standard',
    claimedBy: null,
  },
  {
    id: 'shift-008',
    role: 'Registered Nurse',
    facilityName: 'Hoag Hospital',
    facilityLocation: 'Newport Beach, CA',
    date: '2026-05-18',
    startTime: '07:00',
    endTime: '19:00',
    ratePerHour: 65,
    urgency: 'standard',
    claimedBy: null,
  },
  {
    id: 'shift-009',
    role: 'ICU Nurse',
    facilityName: 'Children\'s Hospital LA',
    facilityLocation: 'Los Angeles, CA',
    date: '2026-05-19',
    startTime: '19:00',
    endTime: '07:00',
    ratePerHour: 84,
    urgency: 'urgent',
    claimedBy: null,
  },
  {
    id: 'shift-010',
    role: 'Certified Nursing Assistant',
    facilityName: 'Glendale Adventist Medical',
    facilityLocation: 'Glendale, CA',
    date: '2026-05-20',
    startTime: '09:00',
    endTime: '17:00',
    ratePerHour: 36,
    urgency: 'standard',
    claimedBy: null,
  },
];

export const MOCK_AUTH_USER = {
  id: 'user-demo-001',
  name: 'Alex Rivera',
  email: 'alex.rivera@email.com',
  type: 'professional' as const,
};
